// Code generated by protoc-gen-go. DO NOT EDIT.
// source: httpgrpc.proto

package httpgrpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// HttpTrailer is the last message sent in a streaming GRPC-over-HTTP
// call, to encode the GRPC status code and any trailer metadata. This
// message is only used in GRPC responses, not in requests.
type HttpTrailer struct {
	Metadata             map[string]*TrailerValues `protobuf:"bytes,1,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Code                 int32                     `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Message              string                    `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Details              []*any.Any                `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *HttpTrailer) Reset()         { *m = HttpTrailer{} }
func (m *HttpTrailer) String() string { return proto.CompactTextString(m) }
func (*HttpTrailer) ProtoMessage()    {}
func (*HttpTrailer) Descriptor() ([]byte, []int) {
	return fileDescriptor_httpgrpc_9cae98b01a653c79, []int{0}
}
func (m *HttpTrailer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpTrailer.Unmarshal(m, b)
}
func (m *HttpTrailer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpTrailer.Marshal(b, m, deterministic)
}
func (dst *HttpTrailer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpTrailer.Merge(dst, src)
}
func (m *HttpTrailer) XXX_Size() int {
	return xxx_messageInfo_HttpTrailer.Size(m)
}
func (m *HttpTrailer) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpTrailer.DiscardUnknown(m)
}

var xxx_messageInfo_HttpTrailer proto.InternalMessageInfo

func (m *HttpTrailer) GetMetadata() map[string]*TrailerValues {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *HttpTrailer) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *HttpTrailer) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *HttpTrailer) GetDetails() []*any.Any {
	if m != nil {
		return m.Details
	}
	return nil
}

type TrailerValues struct {
	Values               []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrailerValues) Reset()         { *m = TrailerValues{} }
func (m *TrailerValues) String() string { return proto.CompactTextString(m) }
func (*TrailerValues) ProtoMessage()    {}
func (*TrailerValues) Descriptor() ([]byte, []int) {
	return fileDescriptor_httpgrpc_9cae98b01a653c79, []int{1}
}
func (m *TrailerValues) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrailerValues.Unmarshal(m, b)
}
func (m *TrailerValues) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrailerValues.Marshal(b, m, deterministic)
}
func (dst *TrailerValues) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrailerValues.Merge(dst, src)
}
func (m *TrailerValues) XXX_Size() int {
	return xxx_messageInfo_TrailerValues.Size(m)
}
func (m *TrailerValues) XXX_DiscardUnknown() {
	xxx_messageInfo_TrailerValues.DiscardUnknown(m)
}

var xxx_messageInfo_TrailerValues proto.InternalMessageInfo

func (m *TrailerValues) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*HttpTrailer)(nil), "librato.grpchan.httpgrpc.HttpTrailer")
	proto.RegisterMapType((map[string]*TrailerValues)(nil), "librato.grpchan.httpgrpc.HttpTrailer.MetadataEntry")
	proto.RegisterType((*TrailerValues)(nil), "librato.grpchan.httpgrpc.TrailerValues")
}

func init() { proto.RegisterFile("httpgrpc.proto", fileDescriptor_httpgrpc_9cae98b01a653c79) }

var fileDescriptor_httpgrpc_9cae98b01a653c79 = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x50, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x25, 0x4d, 0x3f, 0x27, 0x54, 0x64, 0x11, 0x59, 0x7b, 0x0a, 0xbd, 0x34, 0xa7, 0x29, 0xb4,
	0x17, 0x11, 0x3c, 0x28, 0x08, 0x5e, 0x44, 0x58, 0xc4, 0x83, 0xb7, 0x49, 0xb3, 0xa6, 0xc1, 0x34,
	0x1b, 0x36, 0x53, 0x21, 0x7f, 0xc7, 0x5f, 0x2a, 0xd9, 0x24, 0x62, 0x0f, 0xbd, 0xcd, 0xec, 0xfb,
	0x98, 0xf7, 0x16, 0x2e, 0xf6, 0xcc, 0x65, 0x6a, 0xcb, 0x1d, 0x96, 0xd6, 0xb0, 0x11, 0x32, 0xcf,
	0x62, 0x4b, 0x6c, 0xb0, 0x79, 0xdb, 0x53, 0x81, 0x3d, 0xbe, 0xb8, 0x49, 0x8d, 0x49, 0x73, 0xbd,
	0x76, 0xbc, 0xf8, 0xf8, 0xb9, 0xa6, 0xa2, 0x6e, 0x45, 0xcb, 0x9f, 0x01, 0x04, 0xcf, 0xcc, 0xe5,
	0x9b, 0xa5, 0x2c, 0xd7, 0x56, 0xbc, 0xc2, 0xf4, 0xa0, 0x99, 0x12, 0x62, 0x92, 0x5e, 0xe8, 0x47,
	0xc1, 0x66, 0x8b, 0xe7, 0x7c, 0xf1, 0x9f, 0x10, 0x5f, 0x3a, 0xd5, 0x53, 0xc1, 0xb6, 0x56, 0x7f,
	0x26, 0x42, 0xc0, 0x70, 0x67, 0x12, 0x2d, 0x07, 0xa1, 0x17, 0x8d, 0x94, 0x9b, 0x85, 0x84, 0xc9,
	0x41, 0x57, 0x15, 0xa5, 0x5a, 0xfa, 0xa1, 0x17, 0xcd, 0x54, 0xbf, 0x0a, 0x84, 0x49, 0xa2, 0x99,
	0xb2, 0xbc, 0x92, 0x43, 0x77, 0xfd, 0x0a, 0xdb, 0xec, 0xd8, 0x67, 0xc7, 0x87, 0xa2, 0x56, 0x3d,
	0x69, 0x91, 0xc0, 0xfc, 0xe4, 0xb0, 0xb8, 0x04, 0xff, 0x4b, 0xd7, 0xd2, 0x73, 0xb6, 0xcd, 0x28,
	0xee, 0x61, 0xf4, 0x4d, 0xf9, 0xb1, 0x4d, 0x10, 0x6c, 0x56, 0xe7, 0xeb, 0x74, 0x55, 0xde, 0x1b,
	0x76, 0xa5, 0x5a, 0xd5, 0xdd, 0xe0, 0xd6, 0x5b, 0xae, 0x60, 0x7e, 0x82, 0x89, 0x6b, 0x18, 0x3b,
	0xb4, 0x72, 0x7f, 0x34, 0x53, 0xdd, 0xf6, 0x08, 0x1f, 0xd3, 0xde, 0x2d, 0x1e, 0xbb, 0xc4, 0xdb,
	0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9a, 0xad, 0x86, 0x62, 0xa7, 0x01, 0x00, 0x00,
}
